services:
  mysql:
    image: mysql:9.0.1
    container_name: mysqltrincheiras
    environment:
      MYSQL_ROOT_PASSWORD: ${ENV_ROOT_PASSWORD}
      MYSQL_USER: ${ENV_ROOT_USER}
      MYSQL_PASSWORD: ${ENV_MYSQL_PASSWORD}
    ports:
      - "3309:3306"
    volumes:
      - devdojo-db:/var/lib/mysql

volumes:
  devdojo-db: