spring:
#  security:
#    user:
#      name: user
#      password: devdojo

  config:
    import: optional:classpath:.env[.properties]
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://localhost:3309/user_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER:root}
    password: ${ENV_ROOT_PASSWORD:devdojo}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    net.ttddyy.dsproxy.listener: debug
#    org.hibernate.orm.jdbc.bind: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8989

brasil-api:
  base-url: ${BRASIL_API_BASE_URL:https://brasilapi.com.br/api}
  cep-url: ${BRASIL_API_URI:/cep/v1/{cep}}


server:
  port: 8090
