spring:
  application:
    name: anime-service
  threads:
    virtual:
      enabled: true
  flyway:
    enabled: true
  datasource:
    url: jdbc:mysql://localhost:3309/anime_service?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${ENV_ROOT_USER:root}
    password: ${ENV_ROOT_PASSWORD:devdojo}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

server:
  servlet:
    context-path: /
  error:
    include-stacktrace: on_param
  tomcat:
    threads:
      max: 20






